# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16NmGMWf_6p3Ep4GT7Q5SPCNKuemur5YC
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("rasm1.jpg")
cv2_imshow(rasm1)
rasm=cv2.imread("rasm.jpg")
cv2_imshow(rasm)
rasm2=cv2.imread("rasm2.jpg")
cv2_imshow(rasm2)
rasm3=cv2.imread("rasm3.jpg")
cv2_imshow(rasm3)
rasm4=cv2.imread("rasm4.jpg")
cv2_imshow(rasm4)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)